[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains;"
    Content-Security-Policy = "script-src 'self'; style-src 'self';"