[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains;"
    Content-Security-Policy = "script-src 'self' 'unsafe-inline' https://netlify-cdp-loader.netlify.app https://www.redditstatic.com/ads https://tags.srv.stackadapt.com https://cdn.segment.com https://dev.visualwebsiteoptimizer.com https://www.googletagmanager.com https://static.hotjar.com https://connect.facebook.net https://www.googleadservices.com https://bat.bing.com https://snap.licdn.com https://rboid22e.futuresuper.com.au https://s.pinimg.com;"
