[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains;"
    Content-Security-Policy = "script-src 'self' 'unsafe-inline' https://netlify-cdp-loader.netlify.app https://www.redditstatic.com/ads https://tags.srv.stackadapt.com https://cdn.segment.com https://dev.visualwebsiteoptimizer.com https://tags.srv.stackadapt.com;"
