[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains;"
    Content-Security-Policy = "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://media-library.cloudinary.com https://identity.netlify.com https://unpkg.com https://netlify-cdp-loader.netlify.app https://www.redditstatic.com https://tags.srv.stackadapt.com https://cdn.segment.com https://dev.visualwebsiteoptimizer.com https://www.googletagmanager.com https://static.hotjar.com https://script.hotjar.com https://connect.facebook.net https://www.googleadservices.com https://googleads.g.doubleclick.net https://bat.bing.com https://snap.licdn.com https://rboid22e.futuresuper.com.au https://s.pinimg.com https://ct.pinterest.com; https://embed.typeform.com/next/embed.js"
