[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains;"
    Content-Security-Policy = "script-src 'self' 'unsafe-inline' https://netlify-cdp-loader.netlify.app/netlify.js https://www.redditstatic.com/ads/pixel.js https://tags.srv.stackadapt.com/events.js; style-src 'self';"
