backend:
  name: git-gateway
  branch: main

media_library:
  name: cloudinary
  config:
    cloud_name: future-super
    api_key: 749866111487797 # Public Key

publish_mode: editorial_workflow

collections:
  - name: "app"
    label: "App Stories"
    folder: "src/app-posts"
    create: true
    fields:
      - {
          label: "Image",
          name: "image",
          widget: "image",
          hint: "1080px Square, or 1920x1080px Rectangle",
        }
      - {
          label: "Headline",
          name: "headline",
          widget: "string",
          hint: "Max 120 characters",
          required: false,
          pattern: [".{0,120}", "Max 120 characters"],
        }
      - {
          label: "Summary",
          name: "summary",
          widget: "text",
          hint: "One paragraph, no longer than about 4 lines",
          required: false,
        }
      - { label: "Date", name: "date", widget: "datetime" }
      - {
          label: "Read More Link",
          name: "link",
          widget: "string",
          hint: "Include the https://",
          required: false,
        }
  - name: "posts"
    label: "Posts"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "$/layouts/BlogPost.astro",
        }
      - { label: "Image", name: "image", widget: "image" }
      - {
          label: "Tags",
          name: "tags",
          widget: "list",
          hint: "Add as many tags as you like, with a comma seperating each one",
        }
      - { label: "Author", name: "author", widget: "string" }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          hint: "One paragraph, no longer than about 4 lines",
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "documentsAndForms"
    label: "Documents and Forms"
    folder: "src/docs-and-forms"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Document URL", name: "docurl", widget: "string" }
      - {
          label: "Link Type",
          name: "type",
          widget: "select",
          options: ["PDF", "Online", "Contact"],
        }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options:
            [
              "Super Documents",
              "Super Forms",
              "Pension Documents",
              "Pension Forms",
              "Annual Reports",
              "Impact Reports",
              "Employer Forms",
              "Disclosure Requirements",
            ],
        }
      - {
          label: "Order",
          name: "order",
          widget: "number",
          hint: "A number that determines where this will sit in relation to its category siblings",
        }
      - {
          label: "Description",
          name: "body",
          widget: "text",
          hint: "One sentence that briefly describes what this contains",
        }
  - name: "faqs"
    label: "FAQs"
    folder: "src/pages/faqs"
    create: true
    slug: "{{slug}}"
    summary: "{{order}} | {{title}}"
    sortable_fields: ["order"]
    view_groups:
      - label: "Category: "
        field: category
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options:
            [
              "Superannuation Basics",
              "Divestment",
              "Joining",
              "Rolling over",
              "Investments and returns",
              "Contributions and payments to your super",
              "Fees",
              "Insurance",
              "Forms and documents",
              "Managing your account",
              "Member portal instructions",
              "Beneficiaries",
              "Withdrawing from your super",
              "Pension",
              "General",
              "Employers",
              "Advisor information",
            ],
        }
      - {
          label: "Order",
          name: "order",
          widget: "number",
          hint: "A number that determines where this will sit in relation to its category siblings",
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "$/layouts/FaqPage.astro",
        }
  - name: "careers"
    label: "Careers"
    folder: "src/pages/career"
    create: true
    slug: "{{slug}}-{{year}}{{month}}{{day}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Start Date", name: "startDate", widget: "date" }
      - { label: "End Date", name: "endDate", widget: "date" }
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "$/layouts/Career.astro",
        }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Salary", name: "salary", widget: "string", required: false }
      - { label: "Application URL", name: "applicationUrl", widget: "string" }
      - {
          label: "Summary",
          name: "summary",
          widget: "text",
          hint: "One paragraph, no longer than about 4 lines",
        }
      - { label: "Role Description", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Subtitle",
          name: "summary",
          widget: "string",
          required: false,
        }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          hint: "One paragraph, no longer than about 4 lines",
        }
      - { label: "Body", name: "body", widget: "markdown" }
